### ISSUE TITLE
font size calculation

### ISSUE THREAD

**Issue by CaiyiZhu** [mloesch/baposter#1]
Hi there,

I am really confused about the font size. For example, if I am using A0poster, and the fontscale= 0.36, what should the font size be?

In you documentation, you said that the actual font size is "standard font size" * 1/fontscale. What is the  so-called 'standard font size'  for different paper. 

I searched different community including stackover flow and stack exchange, but find no answer.

**Comment by mloesch** [comment]
I'm not the package maintainer, this is just my experimental clone. See http://www.brian-amberg.de/uni/poster/ for the original package.
